# Generated by Django 5.0.7 on 2025-06-17 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('number', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Номер квартиры')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.house')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Intercom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date_setup', models.DateField(verbose_name='Дата установки')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.house')),
            ],
            options={
                'verbose_name': 'Домофон',
                'verbose_name_plural': 'Домофоны',
                'ordering': ['id'],
            },
        ),
    ]
